<a href="https://colab.research.google.com/github/Alsr96/LMMAES/blob/master/LMAES_layerwise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf
import numpy as np
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt

class structtype():
    pass

def nw_to_vec(model,layer_idx=None):
    n_layers = len(model.layers)
    vector=np.empty((0,))
    ind=np.zeros((1,))
    sum_i=0
    if layer_idx==None:
        idx=range(n_layers)
    else:
        idx=layer_idx
    for i in idx:
        if len(model.layers[i].get_weights())==2:
            weights, biases = model.layers[i].get_weights()
            s_w=np.size(weights)
            sum_i=sum_i+s_w
            ind=np.append(ind,sum_i)
            w_v=np.reshape(weights,(s_w,))
            s_b=np.size(biases)
            sum_i=sum_i+s_b
            ind=np.append(ind,sum_i)
            b_v=np.reshape(biases,(s_b,))
            wb=np.append(w_v,b_v)
            vector=np.append(vector,wb)
    return vector, ind

def vec_to_nw(vector,ind,model,layer_idx=None):
    n_layers = len(model.layers)
    if layer_idx==None:
        idx=range(n_layers)
    else:
        idx=layer_idx
    k=0
    for i in idx:
        if len(model.layers[i].get_weights())==2:
            weights,biases=model.layers[i].get_weights()
            j1=k
            j2=k+1
            j3=k+2
            weights=np.reshape(vector[int(ind[j1]):int(ind[j2])],np.shape(weights))
            biases=np.reshape(vector[int(ind[j2]):int(ind[j3])],np.shape(biases))
            model.layers[i].set_weights((weights,biases))
            k=k+2
    return model

#split=[15,15]
def split_data(input_data,target2,split):
    n_samples=len(target2)
    s1_input=input_data[0:int(split[0]*n_samples/(split[0]+split[1]))]
    s1_target=target2[0:int(split[0]*n_samples/(split[0]+split[1]))]
    s2_input=input_data[int(split[0]*n_samples/(split[0]+split[1])):n_samples]
    s2_target=target2[int(split[0]*n_samples/(split[0]+split[1])):n_samples]
    return s1_input, s1_target, s2_input, s2_target

def lmmaes(model,total_input,total_target,split=None,batch=None,n_candidates = None,sigma=1/10,function_budget=10000,function_target=None,itr_limit=20,validation_fail_limit=6,layer_idx=None):
    if split!=None:
        n_validation=int(split[0]*np.shape(total_input)[0]/100)
        n_test=int(split[1]*np.shape(total_input)[0]/100)
        validation_input=total_input[0:n_validation]
        validation_target=total_target[0:n_validation]
        test_input=total_input[n_validation:n_validation+n_test]
        test_target=total_target[n_validation:n_validation+n_test]
        train_input=total_input[n_validation+n_test:np.shape(total_input)[0]]
        train_target=total_target[n_validation+n_test:np.shape(total_target)[0]]
    else:
        train_input=total_input[0]
        train_target=total_target[0]
        validation_input=total_input[1]
        validation_target=total_target[1]
        test_input=total_input[2]
        test_target=total_target[2]
    # converting the weights and biases to a row vector
    y, ind = nw_to_vec(model,layer_idx=layer_idx)
    n_dimensions=0
    validation_fail=0
    if layer_idx==None:
        n_layers = len(model.layers)
        itr = range(n_layers)
    else:
        n_layers = len(layer_idx)
        itr = layer_idx
    for i in itr:
        if len(model.layers[i].get_weights())==2:
            weights, biases = model.layers[i].get_weights()
            n_dimensions=np.size(weights)+np.size(biases)+n_dimensions
    if n_candidates==None:
        n_candidates = 4 + np.floor(3*np.log(n_dimensions))
    mu = np.floor(n_candidates/2)
    w = np.empty([0,0])
    for i in range(int(mu)):
        w = np.append(w,np.log(mu+0.5)-np.log(i+1))
    sum_w = np.sum(w)
    w = w/sum_w
    mu_w = 1/(np.sum(np.square(w)))
    #
    m = 4 + np.floor(3*np.log(n_dimensions))
    c_sigma = 2*n_candidates/n_dimensions
    const1=np.sqrt(mu_w*c_sigma*(2-c_sigma))
    
    c_d = np.empty([0,0])
    c_c = np.empty([0,0])
    const2=np.empty([0,0])
    for i in range(int(m)):
        c_d = np.append(c_d,1/(n_dimensions*(1.5**i)))
        c_c = np.append(c_c,n_candidates/(n_dimensions*(4**i)))
        const2=np.append(const2,np.sqrt(mu_w*c_c[i]*(2-c_c[i])))
    t=0
    func_calls=0
    p_sigma = np.zeros((n_dimensions,))
    m_i = np.zeros((int(m), n_dimensions))
    if batch==None:
        batch=len(train_target)
    
    itr=0
    res=model.evaluate(x=train_input,y=train_target)
    func_calls=func_calls+1
    log_train=np.array([[itr,res[0],res[1]]])
    best_model=model
    best_res=model.evaluate(x=validation_input,y=validation_target)
    func_calls=func_calls+1
    log_validation=np.array([[itr,res[0],res[1],validation_fail]])
    # for testing print(model.layers[0].get_weights(),model.layers[1].get_weights())
    # for testing print(n_dimensions)
    while itr<=itr_limit:
        for k in range(int(len(train_target)/batch)):
            #t, y, p_sigma, sigma = lm_func.step_lmmaes(t,n_dimensions,m,n_candidates,c_c,c_d,loss_func,y,sigma,mu,w,c_sigma,const1,const2,data)
            z=np.random.randn(int(n_candidates),n_dimensions)
            d = np.copy(z)
            f_list=np.empty((int(m),1))
            for i in range(int(m)):
                for j in range(np.minimum(t,int(m))):
                    d[i]=(1-c_d[j])*d[i] + c_d[j]*np.sum(m_i[j]**2)*d[i]#(np.matmul(m_i[j][np.newaxis],np.matmul(np.transpose(m_i[j][np.newaxis]),d[i][np.newaxis])))
                #res = list(map(benchmark_functions.rosenbrock,[y+sigma*d[i]])) ###############
                modeli=vec_to_nw(y+sigma*d[i],ind,model,layer_idx=layer_idx)
                res=modeli.evaluate(x=train_input[batch*k:batch*(k+1)],y=train_target[batch*k:batch*(k+1)],verbose=0)
                func_calls=func_calls+1
                f_list[i][0] = res[0]
            
            #f_list = np.append(f_list, (np.linalg.norm(y))**2)##
            #d = np.append(d, np.zeros((1,n_dimensions)), axis=0)##
            #z = np.append(z, np.zeros((1,n_dimensions)), axis=0)##
            
            sortidx_f = f_list.argsort(axis=0)
            #fjhyt
            sortidx_f = sortidx_f[0:int(mu)]
            best_list = np.empty([int(mu),n_dimensions])
            j = 0
            for i in sortidx_f:
                best_list[j] = w[j]*d[i]
                j = j+1
            y_next = y + sigma*np.sum(best_list,0)
            
            best_list2 = np.empty([int(mu),n_dimensions])
            j = 0
            for i in sortidx_f:
                best_list2[j] = w[j]*z[i]
                j = j+1
            p_sigma_next = (1-c_sigma)*p_sigma + const1*np.sum(best_list2,0)
            mag_p_sigma_next = np.linalg.norm(p_sigma_next)
            for i in range(int(m)):
                m_i[i] = (1-c_c[i])*m_i[i] + const2[i]*np.sum(best_list2,0)
            sigma_next = sigma*np.exp(c_sigma*(((mag_p_sigma_next**2)/n_dimensions)-1)/2)
            t=t+1
            sigma = sigma_next
            p_sigma = p_sigma_next
            y = y_next
            modelt=vec_to_nw(y,ind,model,layer_idx=layer_idx)
            jhlk=sortidx_f[0][0]
            print(f_list[int(jhlk)],t,sigma)
        # for testing print(model.layers[0].get_weights(),model.layers[1].get_weights())
        # for testing dhytd
        #trained_model=model
        itr=itr+1
        res=modelt.evaluate(x=train_input,y=train_target)
        func_calls=func_calls+1
        log_train=np.append(log_train,np.array([[itr,res[0],res[1]]]),axis=0)
        print('train:',[itr,res[0],res[1]*100])
        res=modelt.evaluate(x=validation_input,y=validation_target)
        func_calls=func_calls+1
        if res[1]>best_res[1]:
            best_model=modelt
            best_res=res
            validation_fail=0
        else:
            validation_fail=validation_fail+1
        log_validation=np.append(log_validation,np.array([[itr,res[0],res[1],validation_fail]]),axis=0)
        print('validation:',[itr,res[0],res[1]*100,validation_fail])
        if validation_fail>=validation_fail_limit:
            break
    
    # testing the model
    a=best_model.predict(x=test_input)
    matrix = confusion_matrix(test_target.argmax(axis=1), a.argmax(axis=1))
    cat_acc=np.zeros((np.shape(matrix)[0]+1,))
    sum_cat=0
    for i in range(np.shape(matrix)[0]):
        cat_acc[i]=100*(matrix[i][i]/np.sum(matrix[:,i]))
        sum_cat=sum_cat+matrix[i][i]
    cat_acc[np.shape(matrix)[0]]=100*sum_cat/np.sum(matrix)
    
    # accuracy:- green: validation data, blue: training data
    plt.plot(log_train[:,0],log_train[:,2],'b--',log_train[:,0],log_validation[:,2],'g')
    plt.show()
    # loss:- green: validation data, blue: training data
    plt.plot(log_train[:,0],log_train[:,1],'b--',log_train[:,0],log_validation[:,1],'g')
    plt.show()
    # validation checks
    plt.plot(log_train[:,0],log_validation[:,3],'g.')
    plt.show()
    print(matrix)
    print(cat_acc)
    return model, log_train, log_validation, matrix

In [0]:
from keras.models import Sequential
from keras.layers import Dense, Conv2D, Flatten

from keras.datasets import mnist
#download mnist data and split into train and test sets
(X_train, y_train), (X_test, y_test) = mnist.load_data()
X_train=X_train.reshape(60000,28,28,1)
X_test=X_test.reshape(10000,28,28,1)

from keras.utils import to_categorical
#one-hot encode target column
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

In [0]:
#create model
model = Sequential()
#add model layers
model.add(Conv2D(64, kernel_size=3, activation='relu', input_shape=(28,28,1)))
model.add(Conv2D(32, kernel_size=3, activation='relu'))
model.add(Flatten())
model.add(Dense(10, activation='softmax'))
#compile model using accuracy to measure model performance
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

xtrain,ytrain,xval,yval=split_data(X_train,y_train,[5,1])

In [0]:
trained_model, log_train, log_validation, matrix = lmmaes(model,(xtrain,xval,X_test),(ytrain,yval,y_test),batch=100,itr_limit=19)

model.evaluate(x=X_test,y=y_test)

In [0]:
matrix

log_validation
array([[ 0.        , 12.56754179,  0.05312   ,  0.        ],
       [ 1.        ,  4.14396236,  0.7429    ,  0.        ],
       [ 2.        ,  3.79903511,  0.7643    ,  0.        ],
       [ 3.        ,  2.84162023,  0.8237    ,  0.        ],
       [ 4.        ,  2.74491166,  0.8297    ,  0.        ],
       [ 5.        ,  2.52892918,  0.8431    ,  0.        ],
       [ 6.        ,  2.35968918,  0.8536    ,  0.        ],
       [ 7.        ,  2.47251584,  0.8466    ,  1.        ],
       [ 8.        ,  2.50475204,  0.8446    ,  2.        ],
       [ 9.        ,  2.30327584,  0.8571    ,  0.        ],
       [10.        ,  2.39837261,  0.8512    ,  1.        ],
       [11.        ,  2.45962137,  0.8474    ,  2.        ],
       [12.        ,  2.3129467 ,  0.8565    ,  3.        ],
       [13.        ,  2.45156233,  0.8479    ,  4.        ],
       [14.        ,  2.33228841,  0.8553    ,  5.        ],
       [15.        ,  2.42899699,  0.8493    ,  6.        ]])
log_train
array([[ 0.        , 12.56754179,  0.05312   ],
       [ 1.        ,  4.43473279,  0.72486   ],
       [ 2.        ,  4.02855679,  0.75006   ],
       [ 3.        ,  3.28325605,  0.7963    ],
       [ 4.        ,  3.02149818,  0.81254   ],
       [ 5.        ,  2.81293002,  0.82548   ],
       [ 6.        ,  2.61532217,  0.83774   ],
       [ 7.        ,  2.75361543,  0.82916   ],
       [ 8.        ,  2.77811494,  0.82764   ],
       [ 9.        ,  2.59436865,  0.83904   ],
       [10.        ,  2.65303852,  0.8354    ],
       [11.        ,  2.72363577,  0.83102   ],
       [12.        ,  2.61242091,  0.83792   ],
       [13.        ,  2.71718853,  0.83142   ],
       [14.        ,  2.56116537,  0.8411    ],
       [15.        ,  2.61790107,  0.83758   ]])
matrix
array([[ 907,    1,   11,    2,    4,   26,   16,    2,   10,    1],
       [   0, 1085,    9,    8,    6,    2,    4,    1,   20,    0],
       [  15,   18,  830,   14,   45,    3,   26,   26,   47,    8],
       [  25,   13,   46,  822,    4,   29,    1,   13,   40,   17],
       [   2,    3,    0,    2,  868,    0,   35,    5,   15,   52],
       [  59,   48,    6,   56,   38,  595,   18,    7,   50,   15],
       [  28,    6,   12,    7,   31,   11,  837,    5,   20,    1],
       [   1,   11,   41,    2,   10,    0,    2,  927,    6,   28],
       [   5,   12,   13,   14,    9,   17,    8,   20,  861,   15],
       [   8,    4,    7,   17,   81,    9,   12,   48,   25,  798]])
category wise accuracy
[86.38095238 90.34138218 85.12820513 87.07627119 79.19708029 85.98265896
 87.27841502 87.95066414 78.70201097 85.34759358 85.3       ]
